apiVersion: v2
name: neohoods-space-chart
description: A Helm chart for deploying NeoHoods space app
type: application
version: 0.1.63
appVersion: "1.0.1"
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
