name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        id: chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Deploy
        uses: qcastel/github-actions-update-helm@master
        with:
          branch-name: main

          git-release-bot-name: "bot-theopenshelf"
          git-release-bot-email: "bot@theopenshelf.dev"

          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          repository: git@github.com:neohoods/neohoods-saas.git
          file-path: space-dev/Chart.yaml

          yaml-paths: "dependencies[0].version"

          tag: ${{ steps.chart-releaser.outputs.chart_version }}
          
          gpg-enabled: true
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-key: ${{ secrets.GPG_KEY }}
